#cloud-config
---
ssh_authorized_keys:
  - "ssh-rsa \
  AAAAB3NzaC1yc2EAAAADAQABAAABgQC7O1Y3p4/D2XnWeiMoAx9GYPNCdoe11F1Jy42ZoG\
  iczg6wPvAJhyTzI4q6cTMemZZFDhBLY6RyBWz8yPhIWZIvO+mKxsEuJpg8LSGcgrKmHj9H\
  7OUslXp/ppyPdeqFmKruLxtYpb3/HcZfaktcOAOl9BLXpF6nZzCfP6HVFlX2RdF2akbxJS\
  j1bChlgrgP1WzyGFx7waSupxfhzudXHbUJoq007hnzpeJJJbpv3lATbn/3Bq9GTv2BjZiJ\
  RS7AyvmoYawodjntzeCGI4GlHEfRU8Fsla12lSQ/w4k60/6cLR7eDWZXV+93xIgU25DKMH\
  Gc5aBLJfMa/yQFHrREOGAhk/osO2CBz3J0JUOEDgkSWbEgHgiWZaso4/TSXjoV+kI+2ubv\
  CVcfDBJSItCtaJoTeIRaG/ruYoX+S9Z43V6k2KiMQv69U4K8vDkwqDQdQd2paHFCgorlmk\
  PXTFF2ner78h0RTNB69AaPURV/ljPBOYXPCS4Qy4d9aJpHKeFq7GU="
  - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCysKo75UfUVeWNjg2pQCpwi9h4u3McF9XjdJVDsIuCB6Oem2zjDY3sHtC6SESMctrCagmdzPoHSO1kqfoab/3yIs49K+tMieBWZZ0lZjuU8jj5uZxlZRl8+CX6vhmkgyZOEnSVLe0Q1VIDiyowRMlV642nQJOny+BzpHjsURoxec3Xy/Zcaxc7kaRAjXH51e51FpKJIA7ib5rFXHTVQHJpe9TTIu/2yWgZkM55oY+RbndwBdKp7AkyyCCF0CpF0y3irlslQgwMI3XQoPwIQLJZ/bpiq5exiPG608K7a+5Y3kToWNTxsw5NcXOkimGd4BJ4dLr+KUzvXsjHIyyinC30QWHSAu8UftesvO95WpQOaEKDsqRUlB/s6caraV4QexXpnBC0WjcsQ3I4c6A4gDzkE+C4dPZ1X9k4WhEvIDOGnBhqL+YLs5vg9wJCCF3y56itTA4ieVymjKjj3q0vR5VKQhdLrIp6SAjQOPVf9ok0CYlcCyRGZaCIxcbzuEYGcLE="

package_update: true
package_upgrade: true
package_reboot_if_required: true

write_files:
  - path: /etc/environment
    content: |
      CONTAINER_RUNTIME_ENDPOINT="unix:///run/containerd/containerd.sock"
      EDITOR=/usr/bin/vi
      VISUAL=/usr/bin/vi      
    append: true
...
